services:
  - type: web
    name: kenya_2022_voters_dashboard
    env: python
    buildCommand: |
      /opt/render/project/src/.venv/bin/python3.10 -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python src/app.py

